### ISSUE TITLE
oResultException: No entity found for query

### ISSUE THREAD

**Issue by sdrahnea** [sdrahnea/order-management-system#11]
when create a new order then receive exception:

Caused by: javax.el.ELException: Error reading [clientList] on type [com.oms.controller.UnitController]
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[tomcat-embed-el-8.5.20.jar!/:8.5.20]

2020-03-23 14:45:18.842 ERROR 6619 --- [nio-8081-exec-6] j.e.resource.webcontainer.jsf.context    : javax.persistence.NoResultException: No entity found for query
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532)

**Comment by sdrahnea** [comment]
fix for 0.0.4-SNAPSHOT
