### ISSUE TITLE
received error when create article 

### ISSUE THREAD

**Issue by sdrahnea** [sdrahnea/order-management-system#12]
Caused by: javax.el.ELException: Error reading [providerList] on type [com.oms.controller.UnitController]
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:98) ~[tomcat-embed-el-8.5.20.jar!/:8.5.20]
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176) ~[javax.faces-2.2.14.jar!/:2.2.14]
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203) ~[javax.faces-2.2.14.jar!/:2.2.14]
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169) ~[tomcat-embed-el-8.5.20.jar!/:8.5.20]
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184) ~[tomcat-embed-el-8.5.20.jar!/:8.5.20]
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109) ~[javax.faces-2.2.14.jar!/:2.2.14]
        ... 116 common frames omitted
Caused by: javax.persistence.NoResultException: No entity found for query
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:532) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
        at com.oms.service.AbstractService.findByName(AbstractService.java:45) ~[classes!/:0.0.3-SNAPSHOT]

**Comment by sdrahnea** [comment]
fix start wiht 0.0.4-SNAPSHOT version
